### ISSUE TITLE
EEXIST: file already exists for Chrome unstable M58

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/selenium-assistant#87]
When using `selenium-assistant`'s browser download via [`npm-publish-scripts`](https://github.com/GoogleChrome/npm-publish-scripts), in order to cut a new release of [`sw-toolbox`](https://github.com/GoogleChrome/sw-toolbox), it fails due to the following error. Blowing away my `node_modules`, reinstalling everything with `npm install`, and then running the release process again doesn't help.

```sh
Starting browser download.
fs.js:1019
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EEXIST: file already exists, symlink 'Versions/Current/Default Apps' -> '/Users/jeffy/.selenium-assistant/chrome/unstable/Google Chrome.app/Contents/Versions/58.0.3018.3/Google Chrome Framework.framework/Default Apps'
    at Object.fs.symlinkSync (fs.js:1019:18)
    at copySync (/Users/jeffy/git/sw-toolbox/node_modules/fs-extra/lib/copy-sync/copy-sync.js:52:8)
    at /Users/jeffy/git/sw-toolbox/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:7
    at Array.forEach (native)
    at copySync (/Users/jeffy/git/sw-toolbox/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:14)
    at /Users/jeffy/git/sw-toolbox/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:7
    at Array.forEach (native)
    at copySync (/Users/jeffy/git/sw-toolbox/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:14)
    at /Users/jeffy/git/sw-toolbox/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:7
    at Array.forEach (native)

```

**Comment by jeffposnick** [comment]
Ah, I didn't pick up on the fact that it was caching in `~` rather than in `node_modules`. That explains why blowing away `node_modules` didn't help...

**Comment by gauntface** [comment]
This is so it can cache across projects ;)

**Comment by gauntface** [comment]
When it works :(
